### PR TITLE
Main Menu | Fix & ToS update.

### PR DESCRIPTION
**Pull request by TheRoyalRat**
This pull request focuses on fixing any of the "Hardcoded String" errors on the Main Menu.

@laREiGN 's update for the Terms of Service is also included.

### CODE REVIEW

**Comment by Wolkje** [comment]
Looks good, see no issues

**Review by BSwamHR — APPROVED** [review]
Everything looks functional, without any hard-coded strings. I like how the ToS text is a separate file now!

**Review by laREiGN — APPROVED** [review]
Looks fine. Changing the layout constraints might break the app layout while its emulated/ran on a phone. The current 'parent' constraints put everything in the middle, and the bias offsets them as far as needed horizontally or vertically. This makes sure that the app looks relatively the same on any resolution.

**Comment by TheRoyalRat** [comment]
> Changing the layout constraints might break the app layout while its emulated/ran on a phone.

I have attempted to return all constraint related values to their original value. It should be fixed.

**Pull request merged**
